package_update: true

packages:
  - bc
  - bison
  - build-essential
  - ccache
  - curl
  - flex
  - g++-multilib
  - gcc-multilib
  - git
  - git-lfs
  - gnupg
  - gperf
  - imagemagick
  - lib32readline-dev
  - lib32z1-dev
  - libelf-dev
  - liblz4-tool
  - libsdl1.2-dev
  - libssl-dev
  - libxml2
  - libxml2-utils
  - lzop
  - pngcrush
  - rsync
  - schedtool
  - squashfs-tools
  - xsltproc
  - zip
  - zlib1g-dev
  - wget
  - lib32ncurses5-dev
  - libncurses5
  - libncurses5-dev
  - python-is-python3

write_files:
  - path: /run/setup.sh
    permissions: "0775"
    content: |
      #!/bin/bash
      cd /home/user
      wget -q https://dl.google.com/android/repository/platform-tools-latest-linux.zip -o platform-tools.zip
      unzip platform-tools.zip -d ~
      echo "# add Android SDK platform tools to path
      if [ -d "$HOME/platform-tools" ] ; then
        PATH="$HOME/platform-tools:$PATH"
      fi
      # set PATH so it includes user's private bin if it exists
      if [ -d "$HOME/bin" ] ; then
        PATH="$HOME/bin:$PATH"
      fi" >> ~/.profile
      echo "export USE_CCACHE=1
      export CCACHE_EXEC=/usr/bin/ccache" >> ~/.bashrc
      ccache -M 50G
      mkdir -p ~/bin
      mkdir -p ~/android/lineage
      curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
      chmod a+x ~/bin/repo
      source ~/.profile
      git config --global user.email "placeholder"
      git config --global user.name "placeholder"
      git lfs install
      git config --global trailer.changeid.key "Change-Id"
      cd ~/android/lineage
      repo init -u https://github.com/LineageOS/android.git -b lineage-22.1 --git-lfs

    owner: user:user
runcmd:
  - su user -c "bash /run/setup.sh"
